//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNet.Dominio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factor
    {
        public Factor()
        {
            this.Caracterizacion = new HashSet<Caracterizacion>();
            this.Caracteristica = new HashSet<Caracteristica>();
        }
    
        public int idFactor { get; set; }
        public string nombreFactor { get; set; }
    
        public virtual ICollection<Caracterizacion> Caracterizacion { get; set; }
        public virtual ICollection<Caracteristica> Caracteristica { get; set; }
    }
}
