//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNet.Dominio.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Gerente
    {
        public Gerente()
        {
            this.Proyecto = new HashSet<Proyecto>();
        }
    
        public int idGerente { get; set; }
        
        [Required(ErrorMessage="Este campo es obligatorio")]
        [StringLength(80,ErrorMessage="El nombre es demasiado largo. Se admite hasta 80 caracteres.")]
        [Display(Name="Nombre")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [StringLength(80, ErrorMessage = "El apellido es demasiado largo. Se admite hasta 80 caracteres.")]
        [Display(Name = "Apellido")]
        public string apellido { get; set; }
    
        public virtual ICollection<Proyecto> Proyecto { get; set; }

        public override string ToString()
        {
            return apellido + ", " + nombre;
        }
    }
}
