//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNet.Dominio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public Proyecto()
        {
            this.Caracterizacion = new HashSet<Caracterizacion>();
        }
    
        public int idProyecto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Gerente Gerente { get; set; }
        public virtual ICollection<Caracterizacion> Caracterizacion { get; set; }

        public override string ToString()
        {
            string proyectoToString = "Nombre: '" + nombre
                                        + "'\n Descripcion: '" + descripcion
                                        + "'\n Fecha: " + fecha;
            return proyectoToString;
        }
    }
}
