//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNet.Dominio.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Proyecto
    {
        public Proyecto()
        {
            this.Caracterizacion = new HashSet<Caracterizacion>();
        }

        public int idProyecto { get; set; }

        [Required(ErrorMessage="No puede dejar este campo vacío.")]
        [Display(Name="Nombre")]
        [StringLength(32, ErrorMessage="Se admite hasta 32 caracteres.")]
        public string nombre { get; set; }
        
        [Display(Name="Descripción")]
        [StringLength(100, ErrorMessage = "La descripción es demasiado larga. Se admite hasta 100 caracteres.")]
        public string descripcion { get; set; }

        [Required(ErrorMessage="Elija o escriba una fecha de forma dd-mm-aaaa ó dd/mm/aaaa.")]
        [Display(Name = "Fecha")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fecha { get; set; }
        
        [Display(Name="Gerente")]
        public int Gerente_idGerente { get; set; }

        public virtual Gerente Gerente { get; set; }
        public virtual ICollection<Caracterizacion> Caracterizacion { get; set; }

        public override string ToString()
        {
            string proyectoToString = "Nombre: '" + nombre
                                        + "'\n Descripcion: '" + descripcion
                                        + "'\n Fecha: " + fecha;
            return proyectoToString;
        }
    }
}
