//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caracteristica
    {
        public int idCaracteristica { get; set; }
        public string denominacion { get; set; }
        public Nullable<int> valor { get; set; }
    
        public virtual Factor Factor { get; set; }
    }
}
