//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factor
    {
        public Factor()
        {
            this.Caracteristica = new HashSet<Caracteristica>();
            this.Proyecto = new HashSet<Proyecto>();
            this.Ponderacion = new HashSet<Ponderacion>();
        }
    
        public int idFactor { get; set; }
        public string nombreFactor { get; set; }
    
        public virtual ICollection<Caracteristica> Caracteristica { get; set; }
        public virtual ICollection<Proyecto> Proyecto { get; set; }
        public virtual ICollection<Ponderacion> Ponderacion { get; set; }
    }
}
