//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public Proyecto()
        {
            this.Factor = new HashSet<Factor>();
            this.Ponderacion = new HashSet<Ponderacion>();
        }
    
        public int idProyecto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual ICollection<Factor> Factor { get; set; }
        public virtual Gerente Gerente { get; set; }
        public virtual ICollection<Ponderacion> Ponderacion { get; set; }
    }
}
