//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNet.AccesoDatos
{
    using PNet.Dominio.Modelo;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Modelo1Container : DbContext
    {
        public Modelo1Container()
            : base("name=Modelo1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Factor> FactorSet { get; set; }
        public DbSet<Caracteristica> CaracteristicaSet { get; set; }
        public DbSet<Proyecto> ProyectoSet { get; set; }
        public DbSet<Gerente> GerenteSet { get; set; }
        public DbSet<Caracterizacion> CaracterizacionSet { get; set; }
    }
}
